# Python for AI — Class 13
### NumPy: a tool to work with many numbers

**NumPy** is a Python library. It helps us work with **many numbers at one time**.
AI uses NumPy all the time. Pandas and PyTorch are built on it.

## How we will learn today

Every topic has the same 4 steps:

| Step | What happens |
|------|--------------|
| **CONCEPT** | The teacher explains the idea. Short points. |
| **EXAMPLE** | The teacher types the code. **You type it too** and run it. |
| **QUICK CHECK** | You solve a small task alone. |
| **SOLUTION** | We check the answer together. The solutions are in a separate file. |

**Tips:**
- Run a cell with `Shift + Enter`.
- **BREAKS ON PURPOSE** = the cell shows a red error. This is planned.
- **WRONG ON PURPOSE** = no error, but the answer is not what you think.

# Hour 1: Arrays, Shape and Indexing

## CONCEPT: Why do we need NumPy?

- A Python **list** can hold numbers. But for maths, we need a loop every time.
- NumPy gives us the **array**. An array is a grid of numbers made for fast maths.
- Pandas, scikit-learn and PyTorch all keep their numbers in NumPy arrays.
- Arrays are fast, because NumPy does the loop inside fast C code, not in Python.

### EXAMPLE: Import NumPy

*We call it `np`. Everyone in the world uses this short name.*

In [ ]:
import numpy as np

### EXAMPLE: A list cannot do maths on all numbers

*We want to add 100 to every price.*

In [ ]:
prices_list = [1200, 850, 400, 3500]
print(prices_list + 100)

That is an error. Now let's try `*`:

In [ ]:
print(prices_list * 2)

We wanted to double every price. But the list was **repeated** two times.

### EXAMPLE: The same maths with an array

In [ ]:
prices = np.array([1200, 850, 400, 3500])
print(prices + 100)

In [ ]:
print(prices * 2)

No loop. NumPy does the maths on **every number**. This is called a **vectorized** operation.

### ✏️ QUICK CHECK 1: Your first array

Make an array `my_marks` from the list `[40, 55, 70, 90]`. Print `my_marks + 5`.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Arrays are fast

- A Python loop works on one number at a time.
- NumPy works on all numbers together.
- AI needs billions of calculations. This is why AI uses NumPy.

**Before we run the speed test:** the list side uses a *list comprehension*. It is a short way to write a loop that makes a list.

Normal loop (4 lines):
```python
result = []
for x in numbers:
    result.append(x * 2)
```

List comprehension (1 line, same answer):
```python
result = [x * 2 for x in numbers]
```

How to read it:
```
[ x * 2   for x in numbers ]
  ↑         ↑
  put this  take each x
  in the    from numbers
  new list
```
In words: "For each `x` in `numbers`, put `x * 2` in the new list."

### EXAMPLE: Speed test: 1 million numbers

*`1_000_000` is the same as `1000000`. The `_` only helps us read it.*

In [ ]:
import time

numbers = list(range(1_000_000))
arr = np.array(numbers)

start = time.time()
result = [x * 2 for x in numbers]
print("list  :", time.time() - start, "seconds")

start = time.time()
result = arr * 2
print("array :", time.time() - start, "seconds")

## CONCEPT: Creating arrays

- `np.array(list)` makes an array from a Python list (or a list of lists).
- `np.zeros(n)` and `np.ones(n)` make arrays full of 0s or 1s.
- `np.arange(start, stop, step)` works like `range()`. The stop number is **not** included.
- `np.linspace(start, stop, n)` gives `n` numbers with the same gap. The stop number **is** included.
- `np.random.randint(low, high, size)` gives random whole numbers.

### EXAMPLE: Making arrays a few ways

In [ ]:
a = np.array([10, 20, 30])
print(a)

In [ ]:
print(np.zeros(4))
print(np.ones(4))

In [ ]:
print(np.arange(0, 10, 2))

In [ ]:
print(np.linspace(0, 1, 5))

In [ ]:
print(np.random.randint(0, 100, size=(2, 3)))   # random numbers, 2 rows, 3 columns

### ✏️ QUICK CHECK 2: Making arrays

Make an array `prices` from `[250, 480, 120, 990]`. Then make `zeros_5`, an array of five zeros. Print both.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Dimensions and shape

- A **1-D** array is one row of numbers: `np.array([1, 2, 3])`.
- A **2-D** array is a table (a list of lists): `np.array([[1, 2], [3, 4]])`.
- `.ndim` = how many directions (dimensions).
- `.shape` = size in each direction. For 2-D: `(rows, columns)`.
- `.size` = how many numbers in total.
- `.dtype` = the type of the numbers (`int64`, `float64`).

### EXAMPLE: Look inside an array

*The same 4 things work on any array.*

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid)

In [ ]:
print(grid.ndim)     # 2
print(grid.shape)    # (2, 3) -> 2 rows, 3 columns
print(grid.size)     # 6
print(grid.dtype)    # int64

**Tip:** When something breaks, first print the `shape`. Most NumPy errors are shape errors.

### ✏️ QUICK CHECK 3: Look inside an array

Make a 2-D array `board` from `[[1, 0, 1], [0, 1, 0]]`. Print its `.ndim`, `.shape` and `.size`.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Reshape

- `reshape` keeps the same numbers. It only changes the rows and columns.
- The number of elements must stay the same.
- `-1` means: "NumPy, work this one out for me."

### EXAMPLE: Change the shape

In [ ]:
a = np.arange(12)
print(a)

In [ ]:
print(a.reshape(3, 4))    # 3 rows, 4 columns

In [ ]:
print(a.reshape(4, -1))   # 4 rows, NumPy finds the columns

**BREAKS ON PURPOSE.** 5 × 3 = 15, but we have only 12 numbers:

In [ ]:
a.reshape(5, 3)

### ✏️ QUICK CHECK 4: Reshape

Make an array of the numbers 1 to 6 with `np.arange`. Reshape it to 2 rows and 3 columns. Print it.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Data type (dtype)

- An array keeps **only one type** of data.
- If you put a decimal into a whole-number array, the decimal part is **cut off**. There is no warning.
- If you mix text and numbers, **everything becomes text**.
- If you need decimals, make the array with `dtype=float`.

### EXAMPLE: The dtype problem

In [ ]:
marks = np.array([80, 72, 91])
print(marks.dtype)

**WRONG ON PURPOSE.** We put `85.7` in a whole-number array:

In [ ]:
marks[0] = 85.7
print(marks)

We wrote 85.7. We got 85. The `.7` was lost.

Mixing text and numbers:

In [ ]:
mixed = np.array([1, 2, "3"])
print(mixed, mixed.dtype)

**Fix:** use `dtype=float`.

In [ ]:
marks = np.array([80, 72, 91], dtype=float)
marks[0] = 85.7
print(marks)

### ✏️ QUICK CHECK 5: Data type

Make an array from `[10, 20, 30]` with `dtype=float`. Put `15.5` in the first place. Print it.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Indexing: get one value

- A 1-D array works like a list: `arr[0]`, `arr[-1]`.
- A 2-D array uses **one bracket with a comma**: `grid[row, col]`.
- Counting starts from **0**.
- Negative numbers work too: `grid[-1, -1]` is the last row, last column.

### EXAMPLE: Indexing a 2-D array

In [ ]:
marks = np.array([[80, 72, 91],    # Ali
                  [65, 88, 70],    # Sara
                  [95, 60, 84]])   # Hassan
#                  Eng Maths Sci
print(marks)

In [ ]:
print(marks[0, 0])     # row 0, column 0 -> Ali's English
print(marks[1, 2])     # Sara's Science
print(marks[-1, -1])   # last row, last column -> Hassan's Science

In [ ]:
print(marks[0])        # only the row -> all of Ali's marks

### ✏️ QUICK CHECK 6: Indexing

Make a 2-D array `temps` from `[[30, 32, 31], [28, 29, 27]]`. Row 0 is Karachi, row 1 is Lahore. Print Karachi's middle-day temperature and Lahore's last-day temperature.

Write your code in the cell below.

In [ ]:
# Write your code here

# Hour 2: Slicing, Filters and Totals

## CONCEPT: Slicing: get many values

- Slicing uses `start:stop:step`, like a list. The stop is **not** included.
- `:` alone means **everything** on that axis.
- `marks[:, 1]` means: all rows, column 1.

### EXAMPLE: Slicing a 2-D array

In [ ]:
print(marks[:, 1])     # all rows, column 1 -> everyone's Maths

In [ ]:
print(marks[0:2, :])   # first 2 rows, all columns -> Ali and Sara

In [ ]:
print(marks[:, 1:])    # all rows, columns from 1 -> Maths and Science

### ✏️ QUICK CHECK 7: Slicing

Using `marks`, print only the **Science** marks (the last column) of all students.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: A slice is a view, not a copy

- With a **list**, a slice is a new copy.
- With a **NumPy array**, a slice **points to the same data**.
- If you change the slice, the original changes too.
- If you want a separate copy, use `.copy()`.

### EXAMPLE: The view problem

**WRONG ON PURPOSE.**

In [ ]:
first_row = marks[0]
first_row[0] = 0
print(marks)

We changed `first_row`. But Ali's English in `marks` is also 0 now.

Now the safe way, with `.copy()`:

In [ ]:
marks[0, 0] = 80              # put it back
safe = marks[0].copy()
safe[0] = 0
print(marks[0])               # the original is safe

### ✏️ QUICK CHECK 8: Copy

Make `a = np.array([1, 2, 3])`. Make a copy `b` with `.copy()`. Change `b[0]` to 99. Print `a` and `b`. Is `a` changed?

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Filters: pick values with a condition

- When you compare an array, you get a **True/False** array. It is called a mask.
- Put the mask inside `[ ]`. NumPy keeps only the `True` values.
- `True` counts as 1, so `.sum()` counts how many are `True`.
- For "and", "or", "not" on arrays, use `&`, `|`, `~`. Put brackets around each condition.

### EXAMPLE: Filter without a loop

In [148]:
scores = np.array([45, 82, 67, 91, 38, 74])
print(scores >= 50)

[False  True  True  True False  True]


In [149]:
print(scores[scores >= 50])             # only the passed students

[82 67 91 74]


In [ ]:
print((scores >= 50).sum(), "passed")   # count the True values

In [ ]:
scores[scores < 50] = 50                # grace marks: raise every fail to 50
print(scores)

**BREAKS ON PURPOSE.** We want marks between 50 and 80. Let's use `and`:

In [150]:
scores[scores > 50 and scores < 80]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

`and` can only check one True/False. We gave it six. Use `&` with brackets:

In [ ]:
print(scores[(scores > 50) | (scores < 80)])

[45 82 67 91 38 74]


### ✏️ QUICK CHECK 9: Filter

Make `ages = np.array([12, 25, 17, 30, 8, 41])`. Print only the ages **18 or more**. Then print how many they are.

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Totals: sum, mean, max, min

- These functions turn many numbers into **one answer**.
- `arr.sum()` = total, `arr.mean()` = average, `arr.max()` = biggest, `arr.min()` = smallest.

### EXAMPLE: Totals of the whole array

In [ ]:
marks = np.array([[80, 72, 91],
                  [65, 88, 70],
                  [95, 60, 84]])

print(marks.sum())     # total of all numbers
print(marks.mean())    # average
print(marks.max())     # biggest
print(marks.min())     # smallest

## CONCEPT: axis: rows or columns?

- Most times we want an answer for **each row** or **each column**.
- `axis=0` goes **down** → one answer for each **column** (each subject).
- `axis=1` goes **across** → one answer for each **row** (each student).
- `argmax()` gives the **position** of the biggest number, not the number.

### EXAMPLE: Using axis

*Rows = students, columns = Eng, Maths, Sci.*

In [ ]:
print(marks.mean(axis=0))    # average of each subject

In [ ]:
print(marks.sum(axis=1))     # total of each student

In [ ]:
print(marks.max(axis=0))     # best mark in each subject

In [ ]:
print(marks.argmax(axis=1))  # which student is best in each subject

### ✏️ QUICK CHECK 10: axis

Make `attendance = np.array([[1, 1, 0], [1, 0, 0], [1, 1, 1]])`. Rows are students, columns are days, 1 means present. Print how many days each student was present. (Hint: `.sum(axis=1)`)

Write your code in the cell below.

In [ ]:
# Write your code here

## CONCEPT: Maths functions

- These work on every number in the array.
- `np.sqrt` = square root, `np.abs` = remove minus sign, `np.round(arr, n)` = round to n decimals.

### EXAMPLE: Maths functions

In [ ]:
x = np.array([1, 4, 9, 16])
print (x)
print(np.sqrt(x))

In [ ]:
print(np.abs(np.array([-3, 5, -1])))

In [ ]:
print(np.round(np.array([1.234, 5.678]), 1))

### ✏️ QUICK CHECK 11: Maths functions

Make `x = np.array([-4, 9, -16, 25])`. Print the `np.abs` of it, then the `np.sqrt` of that.

Write your code in the cell below.

In [ ]:
# Write your code here

# Hour 3: Broadcasting and Practice

## CONCEPT: Broadcasting

- You already used it: `prices + 100` added one number to every price.
- NumPy can also use a **small array** with a **big array**. It repeats the small one to fit.
- The rule: the sizes must be the **same**, or one of them must be **1**.
- When you get a broadcast error, `print` both shapes and compare them.

### EXAMPLE: Add a bonus to Maths only

*3 subjects, so the bonus has 3 numbers.*

In [ ]:
bonus = np.array([0, 5, 0])     # Eng, Maths, Sci
print(marks + bonus)

NumPy added `[0, 5, 0]` to **every row**:

```
[[80 72 91]     [0 5 0]
 [65 88 70]  +  [0 5 0]
 [95 60 84]]    [0 5 0]
```

**BREAKS ON PURPOSE.** Only 2 bonus numbers for 3 subjects:

In [ ]:
bad_bonus = np.array([5, 10])
marks + bad_bonus

### ✏️ QUICK CHECK 12: Broadcasting

Using `marks`, give **10 extra marks to English only**. Print the new marks.

Write your code in the cell below.

In [ ]:
# Write your code here

# Small example: electricity bill

A meter reads the units used by 3 homes on 4 days. Each row is one home.

In [ ]:
units = np.array([[5, 6, 4, 7],      # Home 1
                  [10, 12, 9, 11],   # Home 2
                  [3, 2, 4, 3]])     # Home 3
print(units.shape)

**Question 1:** How many units did each home use in total?

In [ ]:
total = units.sum(axis=1)
print(total)

**Question 2:** Each unit costs Rs 40. What is each home's bill?

In [ ]:
bill = total * 40
print(bill)

**Question 3:** Which home pays the most?

In [ ]:
print("Home number:", bill.argmax() + 1)    # +1 because counting starts from 0

**Question 4:** Which day had the most use in total?

In [ ]:
per_day = units.sum(axis=0)
print(per_day)
print("Busiest day:", per_day.argmax() + 1)

We answered all of these with no loops. Real electricity companies do this for millions of homes. The code is the same, only the array is bigger.

# Why AI uses NumPy

AI models only understand numbers. All data becomes arrays:

| Data | Shape |
|------|-------|
| Table of 1000 houses, 5 details each | `(1000, 5)` |
| One black-and-white picture, 28 × 28 pixels | `(28, 28)` |
| One colour picture, 224 × 224 pixels | `(224, 224, 3)` |

# Practice

### ✏️ QUICK CHECK 13: Practice

Make `sales = np.array([[100, 200, 150], [300, 100, 400]])` (2 stores, 3 months). Print each store's total sales. (Hint: `axis=1`)

Write your code in the cell below.

In [ ]:
# Write your code here

### ✏️ QUICK CHECK 14: Practice (Harder)

Use `sales` from above. Print: (1) each store's total, (2) each month's total across both stores, (3) the single highest sale in the whole array.

Write your code in the cell below.

In [ ]:
# Write your code here

### ✏️ QUICK CHECK 15: Practice (Harder)

Temperatures in °C: `[31, 34, 29, 36, 38, 33, 30]`. Change all to Fahrenheit in one line (`F = C × 9/5 + 32`). Print only the days above 95 °F.

Write your code in the cell below.

In [ ]:
# Write your code here

# Home Practice: Interview-Style Questions

1. What is the difference between a Python list and a NumPy array? Why does it matter for speed?
2. Explain broadcasting in your own words. Use an example of one number plus an array.
3. What is the difference between `axis=0` and `axis=1` in `.sum(axis=...)`?
4. Why does changing a slice of an array sometimes change the original array?
5. You have a 2-D array of exam scores. Write one line that gives the average score of each student.
6. Why do AI libraries use NumPy arrays?

**Extra:** Make a `4 × 3` array with `np.arange(12).reshape(4, 3)`. Print the average of each column.

# Key Takeaways

- A NumPy array is a grid of numbers of **one type**, made for fast maths.
- `.shape`, `.ndim`, `.size` and `.dtype` tell you about an array.
- Use `arr[row, col]` to get one value. Use `:` to get many.
- A slice is a **view**. Use `.copy()` for a real copy.
- Use `&`, `|`, `~` (not `and`, `or`, `not`) for filters.
- `axis=0` goes down (columns). `axis=1` goes across (rows).
- Vectorized maths and broadcasting replace loops. This is why NumPy is fast.

**Next class:** Pandas. It is built on top of NumPy.